services:
  mysqldb:
    image: mysql:8.0.31-oracle
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql

  python-api:
    build: ./python-api
    restart: unless-stopped
    ports:
      - "5000:5000"

  app-java:
    build: .
    container_name: ${APP_CONTAINER_NAME_DES}
    ports:
      - "${SPRING_LOCAL_PORT_DES}:${SPRING_DOCKER_PORT_DES}"
    depends_on:
      - mysqldb
    environment:

      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/${MYSQLDB_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${MYSQLDB_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      SERVER_PORT: ${SPRING_DOCKER_PORT_DES}

volumes:
  db:
  postgres-data:
